import { RatingStatistiqueComponent } from './../../tunisian-got-talent/modules/event-management/components/rating-statistique/rating-statistique.component';
import { ShowCategoryComponent } from './../../tunisian-got-talent/modules/event-management/components/show-category/show-category.component';
import { CreateCategoryComponent } from './../../tunisian-got-talent/modules/event-management/components/create-category/create-category.component';
import { CreateEventComponent } from './../../tunisian-got-talent/modules/event-management/components/create-event/create-event.component';
import { authentificationComponent } from './../../shared/authentification/authentification.component';
import { TalenBlockedListComponent } from './../../tunisian-got-talent/modules/talent-management/components/talent-blocked-list/talent-blocked-list.component';
import { TalentStatisticsComponent } from './../../tunisian-got-talent/modules/talent-management/components/talent-statistics/talent-statistics.component';
import { TalentListComponent } from './../../tunisian-got-talent/modules/talent-management/components/talent-list/talent-list.component';
import { ShowEventComponent } from './../../tunisian-got-talent/modules/event-management/components/show-event/show-event.component';
import { Routes } from '@angular/router';

import { HomeComponent } from '../../home/home.component';
import { UserComponent } from '../../user/user.component';
import { TablesComponent } from '../../tables/tables.component';
import { TypographyComponent } from '../../typography/typography.component';
import { IconsComponent } from '../../icons/icons.component';
import { MapsComponent } from '../../maps/maps.component';
import { NotificationsComponent } from '../../notifications/notifications.component';
import { UpgradeComponent } from '../../upgrade/upgrade.component';
import { ForumComponent } from 'app/tunisian-got-talent/modules/forum-management/forum/forum.component';
import { CompetitionListComponent } from 'app/tunisian-got-talent/modules/competition-mangement/competition-list/competition-list.component';
import { CreateCompetitionComponent } from 'app/tunisian-got-talent/modules/competition-mangement/components/create-competition/create-competition.component';
import { CompetitionStatisticsComponent } from 'app/tunisian-got-talent/modules/competition-mangement/components/competition-statistics/competition-statistics.component';

export const AdminLayoutRoutes: Routes = [
    { path: '',      component: authentificationComponent },
    { path: 'talent',      component: HomeComponent },
    { path: 'talentList',      component: TalentListComponent },
    { path: 'TalentStatistics',      component: TalentStatisticsComponent },
    { path: 'TalenBlockedList',      component: TalenBlockedListComponent },
    { path: 'business',           component: UserComponent },
    { path: 'event',          component: ShowEventComponent },
    { path: 'createEvent',          component: CreateEventComponent },
    { path: 'createEvent/:id',          component: CreateEventComponent },
    { path: 'category',          component: ShowCategoryComponent },
    { path: 'createCategory',          component: CreateCategoryComponent },
    { path: 'createCategory/:id',          component: CreateCategoryComponent },
    { path: 'RatingStatistique',          component: RatingStatistiqueComponent },
    { path: 'forum',     component: ForumComponent },
    { path: 'competitions',          component: CompetitionListComponent },
    { path: 'competitions/create',          component: CreateCompetitionComponent },
    { path: 'competitions/statistics',          component: CompetitionStatisticsComponent },
    { path: 'authentification',      component: authentificationComponent },
    { path: 'maps',           component: MapsComponent },
    { path: 'notifications',  component: NotificationsComponent },
    { path: 'upgrade',        component: UpgradeComponent },
];
